require("lua_tests.support.env")
local manual = require("cgas.adapters.manual")
local asc = require("cgas.semantics.asc")

describe("cgas.adapters.manual", function()
    it("creates a runner that updates ASC", function()
        local a = asc.ASC.new({})
        local runner = manual.new(a)
        assert.is_function(runner.update)
        runner:update(0.1)
        assert.is_true(a.time_source:now() >= 0)
    end)

    it("destroys cleanly", function()
        local a = asc.ASC.new({})
        local runner = manual.new(a)
        runner:destroy()
    end)
end)
