require("lua_tests.support.env")
local tag = require("cgas.semantics.tag")

describe("cgas.semantics.tag", function()
    it("creates tags and checks hierarchy", function()
        local t = tag.GameplayTag.new("state.debuff.stun")
        assert.is_true(t:has("state"))
        assert.is_true(t:has("state.debuff"))
        assert.is_true(t:has("state.debuff.stun"))
        assert.is_false(t:has("state.buff"))
    end)

    it("adds and removes tags from container", function()
        local c = tag.GameplayTagContainer.new()
        local t = tag.GameplayTag.new("state.debuff.stun")
        c:add(t)
        assert.is_true(c:has(tag.GameplayTag.new("state.debuff")))
        c:remove(t)
        assert.is_false(c:has(tag.GameplayTag.new("state.debuff.stun")))
    end)

    it("matches query with all/any/none", function()
        local c = tag.GameplayTagContainer.new()
        c:add(tag.GameplayTag.new("a.b"))
        c:add(tag.GameplayTag.new("c.d"))

        local q1 = tag.GameplayTagQuery.new()
        q1.all_tags:add(tag.GameplayTag.new("a.b"))
        assert.is_true(q1:matches(c))

        local q2 = tag.GameplayTagQuery.new()
        q2.any_tags:add(tag.GameplayTag.new("x.y"))
        q2.any_tags:add(tag.GameplayTag.new("c.d"))
        assert.is_true(q2:matches(c))

        local q3 = tag.GameplayTagQuery.new()
        q3.none_tags:add(tag.GameplayTag.new("a.b"))
        assert.is_false(q3:matches(c))
    end)

    it("matches_any and matches_all between containers", function()
        local a = tag.GameplayTagContainer.new()
        a:add(tag.GameplayTag.new("a.b"))
        a:add(tag.GameplayTag.new("c.d"))

        local b = tag.GameplayTagContainer.new()
        b:add(tag.GameplayTag.new("a.b"))

        assert.is_true(a:matches_any(b))
        assert.is_false(a:matches_all(b))
    end)

    it("supports registry validation", function()
        local registry = tag.GameplayTagRegistry.new()
        registry:register("state.debuff.stun")
        assert.is_true(registry:is_valid("state.debuff.stun"))
        assert.is_false(registry:is_valid("state.buff"))
    end)
end)
