require("lua_tests.support.env")
local mini_gas = require("mini_gas")

describe("mini_gas enum", function()
    it("exports all enum tables", function()
        assert.is_table(mini_gas.EModifierOp)
        assert.is_table(mini_gas.EDurationPolicy)
        assert.is_table(mini_gas.EStackingPolicy)
        assert.is_table(mini_gas.EAbilityActivationPolicy)
        assert.is_table(mini_gas.EAttribute)
        assert.is_table(mini_gas.ETag)
        assert.is_table(mini_gas.EAbilityId)
        assert.is_table(mini_gas.EEffectId)
        assert.is_table(mini_gas.EGameplayEvent)
    end)

    it("has correct numeric values for core enums", function()
        assert.equal(1, mini_gas.EModifierOp.Add)
        assert.equal(2, mini_gas.EModifierOp.Multiply)
        assert.equal(3, mini_gas.EModifierOp.Override)
        assert.equal(4, mini_gas.EModifierOp.Compound)

        assert.equal(1, mini_gas.EDurationPolicy.Instant)
        assert.equal(2, mini_gas.EDurationPolicy.Infinite)
        assert.equal(3, mini_gas.EDurationPolicy.HasDuration)

        assert.equal(1, mini_gas.EStackingPolicy.None)
        assert.equal(2, mini_gas.EStackingPolicy.Add)
        assert.equal(3, mini_gas.EStackingPolicy.Replace)
        assert.equal(4, mini_gas.EStackingPolicy.Refresh)

        assert.equal(1, mini_gas.EAbilityActivationPolicy.Passive)
        assert.equal(2, mini_gas.EAbilityActivationPolicy.Active)
        assert.equal(3, mini_gas.EAbilityActivationPolicy.Reactive)
    end)

    it("has placeholder string values for business enums", function()
        assert.equal("attr.none", mini_gas.EAttribute.None)
        assert.equal("tag.none", mini_gas.ETag.None)
        assert.equal("ability.none", mini_gas.EAbilityId.None)
        assert.equal("effect.none", mini_gas.EEffectId.None)
    end)

    it("has lifecycle event values", function()
        assert.equal("event.ability.activated", mini_gas.EGameplayEvent.AbilityActivated)
        assert.equal("event.ability.ended", mini_gas.EGameplayEvent.AbilityEnded)
        assert.equal("event.effect.applied", mini_gas.EGameplayEvent.EffectApplied)
        assert.equal("event.effect.removed", mini_gas.EGameplayEvent.EffectRemoved)
        assert.equal("event.attribute.changed", mini_gas.EGameplayEvent.AttributeChanged)
        assert.equal("event.tag.added", mini_gas.EGameplayEvent.TagAdded)
        assert.equal("event.tag.removed", mini_gas.EGameplayEvent.TagRemoved)
    end)
end)
