require("lua_tests.support.env")
local mini_gas = require("mini_gas")

describe("mini_gas v2 enum", function()
    it("exports only v2 enums", function()
        assert.is_table(mini_gas.EModifierOp)
        assert.is_table(mini_gas.EAbilityActivationPolicy)
        assert.is_table(mini_gas.EEffectTarget)
    end)

    it("has correct modifier op values", function()
        assert.equal(1, mini_gas.EModifierOp.Add)
        assert.equal(2, mini_gas.EModifierOp.Multiply)
        assert.equal(3, mini_gas.EModifierOp.Override)
    end)

    it("has correct activation policy values", function()
        assert.equal(1, mini_gas.EAbilityActivationPolicy.Passive)
    end)

    it("has correct effect target values", function()
        assert.equal(1, mini_gas.EEffectTarget.Self)
        assert.equal(2, mini_gas.EEffectTarget.Other)
        assert.equal(3, mini_gas.EEffectTarget.All)
    end)
end)
