require("lua_tests.support.env")
local mini_gas = require("mini_gas")

describe("mini_gas spec", function()
    it("ability spec stores def_id level and stack", function()
        local spec = mini_gas.AbilitySpec.new("ability.test", 3, 2)
        assert.equal("ability.test", spec.def_id)
        assert.equal(3, spec.level)
        assert.equal(2, spec.stack)
    end)

    it("effect spec stores def_id level and stack", function()
        local spec = mini_gas.EffectSpec.new("effect.test", 5, 4)
        assert.equal("effect.test", spec.def_id)
        assert.equal(5, spec.level)
        assert.equal(4, spec.stack)
    end)

    it("attribute spec stores def_id and level", function()
        local spec = mini_gas.AttributeSpec.new("attr.test", 7)
        assert.equal("attr.test", spec.def_id)
        assert.equal(7, spec.level)
    end)
end)
