require("lua_tests.support.env")
local Timer = require("cgas.core.timer")

describe("cgas.core.timer", function()
    it("advances time", function()
        local t = Timer.new()
        assert.equal(0, t:now())
        t:advance(1.5)
        assert.equal(1.5, t:now())
    end)

    it("applies global dilation", function()
        local t = Timer.new()
        t:set_global_dilation(0.5)
        assert.equal(0.5, t:scale_dt(1, 1.0))
    end)

    it("applies local dilation", function()
        local t = Timer.new()
        t:set_local_dilation(42, 2.0)
        assert.equal(2.0, t:scale_dt(42, 1.0))
    end)

    it("combines global and local dilation", function()
        local t = Timer.new()
        t:set_global_dilation(0.5)
        t:set_local_dilation(7, 2.0)
        assert.equal(1.0, t:scale_dt(7, 1.0))
    end)
end)
