name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lua 5.4
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install local dependencies
        run: ./luarocks install busted

      - name: Run tests
        run: ./busted lua_tests/
